const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.Mouse,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Timer,
		C3.Behaviors.scrollto,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.TemplateName,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Keyboard.Exps.TypedKey,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.System.Exps.left,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Cnds.OnHierarchyReady,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.JavaScriptInEvents.Localize_Event7_Act1,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.JavaScriptInEvents.Localize_Event13_Act1,
		C3.Plugins.Text.Cnds.PickParent,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Keyboard: 0},
	{commands: 0},
	{Mouse: 0},
	{AJAX: 0},
	{Audio: 0},
	{messages: 0},
	{othertext_locals: 0},
	{callstack_messages: 0},
	{callstack_adjust_areas: 0},
	{screen_bg: 0},
	{speed: 0},
	{scanlines: 0},
	{cells: 0},
	{type: 0},
	{setting_id_order: 0},
	{Tween: 0},
	{Text: 0},
	{Sine: 0},
	{crosshair: 0},
	{targ_x: 0},
	{targ_y: 0},
	{MoveTo: 0},
	{enemy: 0},
	{lx: 0},
	{ly: 0},
	{block: 0},
	{bp: 0},
	{pulse: 0},
	{email_message_elem: 0},
	{id: 0},
	{message_parent: 0},
	{message_dialog: 0},
	{side: 0},
	{mask_mails: 0},
	{backspace_hold: 0},
	{Timer: 0},
	{global_obj: 0},
	{monitor: 0},
	{board: 0},
	{icons: 0},
	{screen_center_x: 0},
	{screen_center_y: 0},
	{ScrollTo: 0},
	{cam: 0},
	{blink: 0},
	{settings_bar_elem: 0},
	{select_setting: 0},
	{fire_effect: 0},
	{art_endgame: 0},
	{cursor_mask: 0},
	{noise: 0},
	{command_text: 0},
	{gameplay_state: 0},
	{cheats_allowed: 0},
	{show_cursor: 0},
	{cursor_char: 0},
	{first_char: 0},
	{first_command: 0},
	{first_value: 0},
	{second_command: 0},
	{second_value: 0},
	{third_command: 0},
	{fc_y: 0},
	{sc_y: 0},
	{tc_y: 0},
	{fire_after: 0},
	{multiplier: 0},
	{x: 0},
	{y: 0},
	{active: 0},
	{color: 0},
	{find_nearest_unblocked_bp: 0},
	{random_x: 0},
	{random_y: 0},
	{continue: 0},
	{chance: 0},
	{enemy_type_name: 0},
	{shoot_radius: 0},
	{found: 0},
	{start_x: 0},
	{start_y: 0},
	{width: 0},
	{height: 0},
	{adjust_was_this_tick: 0},
	{increase_enemies_rate: 0},
	{new_message_x: 0},
	{new_message_y: 0},
	{offset_between_messages_y: 0},
	{new_messages_count: 0},
	{message_was_this_tick: 0},
	{top: 0},
	{tutor: 0},
	{story_stage: 0},
	{kills: 0},
	{first_return_to_gameplay: 0},
	{typewritetext_speed: 0},
	{setting_selected_type: 0},
	{last_gameplay_state: 0},
	{setting_selected_id: 0},
	{volume_value_setting: 0},
	{volume: 0},
	{add: 0},
	{langcode: 0},
	{lang: 0},
	{bf_x: 0},
	{bf_y: 0},
	{bf_w: 0},
	{bf_h: 0},
	{c_w: 0},
	{c_h: 0},
	{bf_left_x: 0},
	{bf_left_y: 0},
	{scan_rate_seconds: 0},
	{scan_time: 0},
	{enemy_spawn_rate_seconds: 0},
	{enemy_spawn_rate_endgame: 0},
	{email_step: 0},
	{selected_message_id: 0},
	{highest_id_messages: 0},
	{lerpfactor: 0},
	{ajax_blocked: 0},
	{dist_x: 0},
	{dist_y: 0},
	{ang_to_center: 0},
	{x_multiplier: 0},
	{y_multiplier: 0},
	{x_limit: 0},
	{y_limit: 0},
	{offset_max: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	commands: class extends self.IArrayInstance {},
	Mouse: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	messages: class extends self.IArrayInstance {},
	othertext_locals: class extends self.IArrayInstance {},
	callstack_messages: class extends self.IArrayInstance {},
	callstack_adjust_areas: class extends self.IArrayInstance {},
	screen_bg: class extends self.ISpriteInstance {},
	scanlines: class extends self.ITiledBackgroundInstance {},
	cells: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	crosshair: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	bp: class extends self.ISpriteInstance {},
	pulse: class extends self.ISpriteInstance {},
	email_message_elem: class extends self.ISpriteInstance {},
	message_parent: class extends self.ISpriteInstance {},
	message_dialog: class extends self.ISpriteInstance {},
	mask_mails: class extends self.ISpriteInstance {},
	global_obj: class extends self.ISpriteInstance {},
	monitor: class extends self.ISpriteInstance {},
	board: class extends self.ISpriteInstance {},
	icons: class extends self.ISpriteInstance {},
	cam: class extends self.ISpriteInstance {},
	blink: class extends self.ISpriteInstance {},
	settings_bar_elem: class extends self.ISpriteInstance {},
	select_setting: class extends self.ISpriteInstance {},
	fire_effect: class extends self.ISpriteInstance {},
	art_endgame: class extends self.ISpriteInstance {},
	cursor_mask: class extends self.ISpriteInstance {},
	noise: class extends self.ISpriteInstance {}
}