const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.Mouse,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.JavaScriptInEvents.Main_es_Event9_Act1,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Keyboard.Exps.TypedKey,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.BBoxLeft,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.BBoxBottom,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TiledBg.Exps.BBoxTop,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.TiledBg.Exps.BBoxRight,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Keyboard: 0},
	{Localization: 0},
	{Mouse: 0},
	{AJAX: 0},
	{Audio: 0},
	{screen_bg: 0},
	{speed: 0},
	{scanlines: 0},
	{cells: 0},
	{type: 0},
	{Tween: 0},
	{Text: 0},
	{Sine: 0},
	{crosshair: 0},
	{MoveTo: 0},
	{enemy: 0},
	{lx: 0},
	{ly: 0},
	{bp: 0},
	{pulse: 0},
	{command_text: 0},
	{gameplay_state: 0},
	{langcode: 0},
	{lang: 0},
	{show_cursor: 0},
	{cursor_char: 0},
	{first_char: 0},
	{first_command: 0},
	{first_value: 0},
	{second_command: 0},
	{second_value: 0},
	{third_command: 0},
	{fc_y: 0},
	{sc_y: 0},
	{tc_y: 0},
	{fire_after: 0},
	{bf_x: 0},
	{bf_y: 0},
	{bf_w: 0},
	{bf_h: 0},
	{c_w: 0},
	{c_h: 0},
	{bf_left_x: 0},
	{bf_left_y: 0},
	{scan_rate_seconds: 0},
	{scan_time: 0},
	{enemy_spawn_rate_seconds: 0},
	{random_x: 0},
	{random_y: 0},
	{continue: 0},
	{chance: 0},
	{enemy_type_name: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Localization: class extends self.IArrayInstance {},
	Mouse: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	screen_bg: class extends self.ISpriteInstance {},
	scanlines: class extends self.ITiledBackgroundInstance {},
	cells: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	crosshair: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	bp: class extends self.ISpriteInstance {},
	pulse: class extends self.ISpriteInstance {}
}